services:
  backend:
    image: backend-test
    build:
      context: .
      dockerfile: test.Dockerfile
    container_name: backend-test
    ports:
      - 3000:3000
    depends_on:
      - db
    command: npm run dev

 
  db:
    image: postgres:14
    container_name: postgres-test
    hostname: postgres
    ports:
      - 3002:5432
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_city_bike_db
    volumes:
      - ./test-db/:/docker-entrypoint-initdb.d/
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"